ecommerce/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

from products import views

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.all, name='products'),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(null=True, blank=True)
	price = models.DecimalField(max_digits=100, decimal_places=2, default=29.89)
	sale_price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
	slug = models.SlugField()
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return str(self.title)


class ProductImage(models.Model):
	Product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(null=True, blank=True)
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.Product.title

products/views.py
from django.shortcuts import render
from products.models import Product


def home(request):
	products = Product.objects.all()
	context = {'products': products}
	template = 'products/home.html'
	return render(request, template, context)

def all(request):
	products = Product.objects.all()
	context = {'products': products}
	template = 'products/all.html'
	return render(request, template, context)

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>{% block title %}{% endblock title %} CFE Ecommerce</title>

    <!-- <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-static/"> -->
    
    <!-- Bootstrap core CSS -->
<!-- <link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Favicons -->

<!-- <link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png"> -->
<!-- <link rel="icon" href="https://getbootstrap.com/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png"> -->
  <link rel="icon" href="{% static 'images/favicon-32x32.png' %}" sizes="16x16" type="image/png">
  <link rel="icon" href="{% static 'images/favicon-16x16.png' %}" sizes="16x16" type="image/png">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.5/examples/navbar-static/navbar-top.css" rel="stylesheet">
  </head>
  <body>

    {% include 'navbar.html' %}

    <div class="container">
      {% block content %}

      {% endblock content %}
      </div>
    
  </body>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
      <!-- <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js"></script></body> -->
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="{% url 'home' %}">CFE Ecommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'products' %}">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>

templates/products/all.html
{% extends 'base.html' %}

{% block title %}
	Products
{% endblock title %}
{% block content %}
	<div class="row">
		{% for product in products %}
		<div class="col-sm-3">
			{% for item in product.productimage_set.all %}
				{% if item.featured %}
				<img src="{{ item.image.url }}" height="60px" width="60px">
				{% endif %}
			
			{% endfor %}
				{{product.id}}
				{{product.title}}
				{{product.price}}
			</div>
	{% cycle "" "" "" "</div><br><hr><div class='row'>" %}
		{% endfor %}
	</div>
{% endblock content %}

templates/products/home.html
{% extends 'base.html' %}

{% block title %}
	Welcome to
{% endblock title %}

{% block content %}
<main role="main" class="container">
  <div class="jumbotron">
    <h1>Hello {% if user.is_authenticated %}{{user.username}} {% else %} Anonymous {% endif %}</h1>
    <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
    <a class="btn btn-lg btn-primary" href="/docs/4.5/components/navbar/" role="button">View navbar docs &raquo;</a>
  </div>
</main>
{% endblock content %}